services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql1
      MYSQL_PASSWORD: mysql2
      MYSQL_ROOT_PASSWORD: mysql3
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: